app/users/routes.py
from flask import render_template, url_for, flash, redirect, request, Blueprint
from flask_login import login_user, current_user, logout_user, login_required
from app import db, bcrypt
from app.models import User
from app.users.forms import (RegistrationForm, LoginForm, UpdateAccountForm,
                             RequestResetForm, ResetPasswordForm)
from app.users.utils import save_picture, send_reset_email

users = Blueprint('users', __name__)


@users.route("/register", methods=['GET', 'POST'])
def register():
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    form = RegistrationForm()
    if form.validate_on_submit():
        hashed_password = bcrypt.generate_password_hash(form.password.data).decode('utf-8')
        user = User(username=form.username.data, email=form.email.data, password=hashed_password)
        db.session.add(user)
        db.session.commit()
        flash('Account Created', 'success')
        flash('You are now able to log in', 'msg')
        return redirect(url_for('users.login'))
    return render_template('authentication/register.html', title='Register', form=form)


@users.route("/login", methods=['GET', 'POST'])
def login():
    if current_user.is_authenticated:
        return redirect(url_for('main.dashboard'))
    form = LoginForm()
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        if user and bcrypt.check_password_hash(user.password, form.password.data):
            login_user(user, remember=form.remember.data)
            return redirect(url_for('main.dashboard'))
        else:
            flash('Login Unsuccessful', 'danger')
            flash('Please check email and password', 'msg')
    return render_template('authentication/login.html', title='Login', form=form)


@users.route("/logout")
def logout():
    logout_user()
    return redirect(url_for('main.route_default'))


@users.route("/account", methods=['GET', 'POST'])
@login_required
def account():
    form = UpdateAccountForm()
    if form.validate_on_submit():
        if form.picture.data:
            picture_file = save_picture(form.picture.data)
            current_user.image_file = picture_file
        current_user.username = form.username.data
        current_user.email = form.email.data
        db.session.commit()
        flash('Your account has been updated!', 'success')
        return redirect(url_for('users.account'))
    elif request.method == 'GET':
        form.username.data = current_user.username
        form.email.data = current_user.email
    image_file = url_for('static', filename='profile_pics/' + current_user.image_file)
    return render_template('account.html', title='Account',
                           image_file=image_file, form=form)


@users.route("/reset_password", methods=['GET', 'POST'])
def reset_request():
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    form = RequestResetForm()
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        send_reset_email(user)
        flash('An email has been sent with instructions to reset your password.', 'info')
        return redirect(url_for('users.login'))
    return render_template('reset_request.html', title='Reset Password', form=form)


@users.route("/reset_password/<token>", methods=['GET', 'POST'])
def reset_token(token):
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    user = User.verify_reset_token(token)
    if user is None:
        flash('That is an invalid or expired token', 'warning')
        return redirect(url_for('users.reset_request'))
    form = ResetPasswordForm()
    if form.validate_on_submit():
        hashed_password = bcrypt.generate_password_hash(form.password.data).decode('utf-8')
        user.password = hashed_password
        db.session.commit()
        flash('Your password has been updated! You are now able to log in', 'success')
        return redirect(url_for('users.login'))
    return render_template('reset_token.html', title='Reset Password', form=form)


# Tabler
@users.route("/sign_in", methods=['GET', 'POST'])
def sign_in():
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    form = LoginForm()
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        if user and bcrypt.check_password_hash(user.password, form.password.data):
            login_user(user, remember=form.remember.data)
            next_page = request.args.get('next')
            return redirect(next_page) if next_page else redirect(url_for('main.home'))
        else:
            flash('Login Unsuccessful. Please check email and password', 'danger')
    return render_template('authentication/sign_in.html', title='Sign In', form=form)


@users.route("/sign_up", methods=['GET', 'POST'])
def sign_up():
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    form = RegistrationForm()
    if form.validate_on_submit():
        hashed_password = bcrypt.generate_password_hash(form.password.data).decode('utf-8')
        user = User(username=form.username.data, email=form.email.data, password=hashed_password)
        db.session.add(user)
        db.session.commit()
        flash('Your account has been created! You are now able to log in', 'success')
        return redirect(url_for('users.sign_in'))
    return render_template('authentication/sign_up.html', title='Sign Up', form=form)


@users.route("/forgot_password", methods=['GET', 'POST'])
def forgot_password():
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    form = RequestResetForm()
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        send_reset_email(user)
        flash('An email has been sent with instructions to reset your password.', 'info')
        return redirect(url_for('users.sign_in'))
    return render_template('authentication/forgot_password.html', title='Forgot Password', form=form)


@users.route("/terms_of_service")
def terms_of_service():
    return render_template('authentication/terms_of_service.html', title='Terms of Service')


@users.route("/auth_lock")
def auth_lock():
    return render_template('authentication/auth_lock.html', title='Screen Locked')

app/templates/authentication/login.html
<!doctype html>
<html lang="en" xmlns="http://www.w3.org/1999/html">
  <head>
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1, viewport-fit=cover"/>
    <meta http-equiv="X-UA-Compatible" content="ie=edge"/>
    {% if title %}
        <title>{{ title }} - Server UI</title>
    {% else %}
        <title>Server UI</title>
    {% endif %}
    <!-- CSS files -->
    <link href="{{ url_for('static', filename='css/tabler.min.css') }}" rel="stylesheet"/>
    <link href="{{ url_for('static', filename='css/tabler-flags.min.css') }}" rel="stylesheet"/>
    <link href="{{ url_for('static', filename='css/tabler-payments.min.css') }}" rel="stylesheet"/>
    <link href="{{ url_for('static', filename='css/tabler-vendors.min.css') }}" rel="stylesheet"/>
    <link href="{{ url_for('static', filename='css/demo.min.css') }}" rel="stylesheet"/>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.3.0/font/bootstrap-icons.css" />
  </head>
  <body  class=" border-top-wide border-primary d-flex flex-column">
    <div class="page page-center">
      <div class="container-tight py-4">
        <div class="text-center mb-4">
          <a href="." class="navbar-brand navbar-brand-autodark"><img src="{{ url_for('static', filename='logo.svg') }}" height="36" alt=""></a>
        </div>
        <form class="card card-md" action="" method="post" autocomplete="off">
            {{ form.hidden_tag() }}
          <div class="card-body">
            <h2 class="card-title text-center mb-4">Login to your account</h2>
            <div class="mb-3">
              {{ form.email.label(class="form-control-label form-label") }}
                {% if form.email.errors %}
                        {{ form.email(type="email", class="form-control is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.email.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.email(type="email", class="form-control", placeholder="Enter email") }}
                    {% endif %}
            </div>
            <div class="mb-2">
              {{ form.password.label(class="form-control-label form-label") }}
              <div class="input-group input-group-flat">
                  {% if form.password.errors %}
                        {{ form.password(id="password", type="password", class="form-control is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.password.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.password(id="password", type="password", class="form-control",  placeholder="Password",  autocomplete="off") }}
                    {% endif %}
                <span class="input-group-text">
                  <i class="bi bi-eye-slash" id="togglePassword"></i>
                </span>
              </div>
            </div>
            <div class="mb-2">
              <label class="form-check">
                {{ form.remember(type="checkbox", class="form-check-input") }}
                <span class="form-check-label">{{ form.remember.label(class="form-check-label") }}</span>
              </label>
                <span class="form-label-description">
                  <a href="{{ url_for('users.forgot_password') }}">I forgot my password</a>
                </span>
            </div>
            <div class="form-footer">
                {{ form.submit(class="btn btn-primary w-100") }}
            </div>
          </div>
        </form>
        <div class="text-center text-muted mt-3">
          Don't have an account yet? <a href="{{ url_for('users.register') }}" tabindex="-1">Sign up</a>
        </div>
      </div>
    </div>

    <!-- Tabler Core -->
    <script src="{{ url_for('static', filename='js/tabler.min.js') }}"></script>
    <script src="{{ url_for('static', filename='js/demo.min.js') }}"></script>
    <script>
        const togglePassword = document.querySelector("#togglePassword");
        const password = document.querySelector("#password");

        togglePassword.addEventListener("click", function () {
            // toggle the type attribute
            const type = password.getAttribute("type") === "password" ? "text" : "password";
            password.setAttribute("type", type);

            // toggle the icon
            this.classList.toggle("bi-eye");
        });
    </script>

    <!-- Bootstrap Toast Messages -->
    <script>
            window.onload = (event)=> {
            let myAlert = document.querySelector('.toast');
            let bsAlert = new  bootstrap.Toast(myAlert);
            bsAlert.show()}
    </script>

      {% with messages = get_flashed_messages(with_categories=true, category_filter=["danger"]) %}
        {% if messages %}
            {% for category, message in messages %}
                  <div class="position-fixed bottom-0 end-0 p-3" style="z-index: 11">
                      <div id="liveToast" class="toast align-items-center text-white bg-{{ category }} border-0" role="alert" aria-live="assertive" aria-atomic="true" data-delay="20000">
                              <div class="toast-header">
                              <strong class="me-auto">{{ message }}</strong>
                              <button type="button" class="btn-close" data-bs-dismiss="toast" aria-label="Close"></button>
                          </div>
            {% endfor %}
        {% endif %}
    {% endwith %}

      {% with messages = get_flashed_messages(with_categories=true, category_filter=["success"]) %}
        {% if messages %}
            {% for category, message in messages %}
                  <div class="position-fixed bottom-0 end-0 p-3" style="z-index: 11">
                      <div id="liveToast" class="toast align-items-center text-white bg-{{ category }} border-0" role="alert" aria-live="assertive" aria-atomic="true" data-delay="20000">
                              <div class="toast-header">
                              <strong class="me-auto">{{ message }}</strong>
                              <button type="button" class="btn-close" data-bs-dismiss="toast" aria-label="Close"></button>
                          </div>
            {% endfor %}
        {% endif %}
    {% endwith %}

    {% with messages = get_flashed_messages(category_filter=["msg"]) %}
        {% if messages %}
            {% for message in messages %}
                            <div class="toast-body">
                                {{ message }}
                            </div>
                          </div>
                      </div>
                  </div>
            {% endfor %}
        {% endif %}
    {% endwith %}

  </body>
</html>

app/templates/authentication/register.html
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1, viewport-fit=cover"/>
    <meta http-equiv="X-UA-Compatible" content="ie=edge"/>
    {% if title %}
        <title>{{ title }} - Server UI</title>
    {% else %}
        <title>Server UI</title>
    {% endif %}
    <!-- CSS files -->
    <link href="{{ url_for('static', filename='css/tabler.min.css') }}" rel="stylesheet"/>
    <link href="{{ url_for('static', filename='css/tabler-flags.min.css') }}" rel="stylesheet"/>
    <link href="{{ url_for('static', filename='css/tabler-payments.min.css') }}" rel="stylesheet"/>
    <link href="{{ url_for('static', filename='css/tabler-vendors.min.css') }}" rel="stylesheet"/>
    <link href="{{ url_for('static', filename='css/demo.min.css') }}" rel="stylesheet"/>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.3.0/font/bootstrap-icons.css" />
  </head>
  <body  class=" border-top-wide border-primary d-flex flex-column">
    <div class="page page-center">
      <div class="container-tight py-4">
        <div class="text-center mb-4">
          <a href="." class="navbar-brand navbar-brand-autodark"><img src="{{ url_for('static', filename='logo.svg') }}" height="36" alt=""></a>
        </div>
        <form class="card card-md" action="" method="post">
          {{ form.hidden_tag() }}
          <div class="card-body">
            <h2 class="card-title text-center mb-4">Create new account</h2>
            <div class="mb-3">
              {{ form.username.label(class="form-control-label form-label") }}
              {% if form.username.errors %}
                        {{ form.username(class="form-control is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.username.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.username(class="form-control", placeholder="Enter name") }}
                    {% endif %}
            </div>
            <div class="mb-3">
              {{ form.email.label(class="form-control-label form-label") }}
              {% if form.email.errors %}
                        {{ form.email(class="form-control is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.email.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.email(class="form-control", placeholder="Enter email") }}
                    {% endif %}
            </div>
            <div class="mb-3">
              {{ form.password.label(class="form-control-label form-label") }}
              <div class="input-group input-group-flat">
                {% if form.password.errors %}
                        {{ form.password(class="form-control is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.password.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.password(class="form-control", placeholder="Password", autocomplete="off") }}
                    {% endif %}
                <span class="input-group-text">
                  <a href="#" class="link-secondary" title="Show password" data-bs-toggle="tooltip"><!-- Download SVG icon from http://tabler-icons.io/i/eye -->
                    <svg xmlns="http://www.w3.org/2000/svg" class="icon" width="24" height="24" viewBox="0 0 24 24" stroke-width="2" stroke="currentColor" fill="none" stroke-linecap="round" stroke-linejoin="round"><path stroke="none" d="M0 0h24v24H0z" fill="none"/><circle cx="12" cy="12" r="2" /><path d="M22 12c-2.667 4.667 -6 7 -10 7s-7.333 -2.333 -10 -7c2.667 -4.667 6 -7 10 -7s7.333 2.333 10 7" /></svg>
                  </a>
                </span>
              </div>
            </div>

            <div class="mb-3">
              {{ form.confirm_password.label(class="form-control-label form-label") }}
              <div class="input-group input-group-flat">
                  {% if form.confirm_password.errors %}
                        {{ form.confirm_password(class="form-control is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.confirm_password.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.confirm_password(class="form-control", placeholder="Confirm password", autocomplete="off") }}
                    {% endif %}
                <span class="input-group-text">
                  <a href="#" class="link-secondary" title="Show password" data-bs-toggle="tooltip"><!-- Download SVG icon from http://tabler-icons.io/i/eye -->
                    <svg xmlns="http://www.w3.org/2000/svg" class="icon" width="24" height="24" viewBox="0 0 24 24" stroke-width="2" stroke="currentColor" fill="none" stroke-linecap="round" stroke-linejoin="round"><path stroke="none" d="M0 0h24v24H0z" fill="none"/><circle cx="12" cy="12" r="2" /><path d="M22 12c-2.667 4.667 -6 7 -10 7s-7.333 -2.333 -10 -7c2.667 -4.667 6 -7 10 -7s7.333 2.333 10 7" /></svg>
                  </a>
                </span>
              </div>
            </div>

            <div class="form-footer">
                {{ form.submit(class="btn btn-primary w-100") }}

            </div>
          </div>
        </form>
        <div class="text-center text-muted mt-3">
          Already have account? <a href="{{ url_for('users.login') }}" tabindex="-1">Sign in</a>
        </div>
      </div>
    </div>
    <!-- Libs JS -->
    <!-- Tabler Core -->
    <script src="{{ url_for('static', filename='js/tabler.min.js') }}"></script>
    <script src="{{ url_for('static', filename='js/demo.min.js') }}"></script>
  </body>
</html>